const BLOGS_ACTION_TYPES = {
    SET_BLOGS_MAPS: 'SET_BLOGS_MAP',
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED: 'FETCH_CATEGORIES_FAILED'
}

export default BLOGS_ACTION_TYPES;